#!/bin/bash

echo "🔧 Ranger Policy Configuration Guide"
echo "=================================="
echo ""
echo "Your Ranger integration is working perfectly! The error you saw is expected -"
echo "Ranger is correctly denying access because no policies are configured yet."
echo ""
echo "To fix this, you need to configure Ranger policies:"
echo ""
echo "1. 🌐 Access Ranger Admin UI:"
echo "   URL: http://localhost:6080"
echo "   Username: admin"
echo "   Password: rangeradmin1"
echo ""
echo "2. 📋 Create Hive Service (if not exists):"
echo "   - Go to 'Access Manager' → 'Resource Based Policies'"
echo "   - Click 'Add New Service' → 'Hive'"
echo "   - Service Name: hive"
echo "   - Username: admin"
echo "   - Password: rangeradmin1"
echo "   - JDBC URL: jdbc:mysql://mysql:3306/hive_metastore"
echo ""
echo "3. 🔐 Create Policy for spark_user:"
echo "   - Go to the 'hive' service"
echo "   - Click 'Add New Policy'"
echo "   - Policy Name: spark_user_access"
echo "   - Database: default"
echo "   - Table: *"
echo "   - Column: *"
echo "   - User: spark_user"
echo "   - Permissions: SELECT, CREATE, INSERT, UPDATE, DELETE, ALL"
echo ""
echo "4. 🔐 Create Policy for longvk user:"
echo "   - Policy Name: longvk_access"
echo "   - Database: default"
echo "   - Table: *"
echo "   - Column: *"
echo "   - User: longvk"
echo "   - Permissions: SELECT, CREATE, INSERT, UPDATE, DELETE, ALL"
echo ""
echo "5. 🧪 Test the connection:"
echo "   # Test with spark_user:"
echo "   beeline -u 'jdbc:hive2://spark-thrift-server:10000' -n spark_user"
echo ""
echo "   # Test with longvk:"
echo "   beeline -u 'jdbc:hive2://spark-thrift-server:10000' -n longvk"
echo ""
echo "6. 📊 Monitor Audit Logs:"
echo "   - Check Elasticsearch: http://localhost:9200"
echo "   - Index: ranger_audits"
echo ""
echo "✅ Once policies are configured, your users will have access!"
echo ""
echo "Current Status:"
echo "✅ Ranger Admin: http://localhost:6080"
echo "✅ Spark Thrift Server: localhost:10000"
echo "✅ Authorization: Working (denying access as expected)"
echo "⏳ Next Step: Configure policies in Ranger Admin UI" 