#!/bin/bash

echo "🔧 Fixing Ranger Policy for spark_user"
echo "======================================"
echo ""

echo "1. 📋 Current Issue Analysis:"
echo "----------------------------"
echo "❌ Policy 'all - database, udf' has isDenyAllElse: true"
echo "❌ This policy only allows: hive, {OWNER}"
echo "❌ spark_user is not in the allowed users list"
echo "❌ This policy covers all databases including 'default'"
echo ""

echo "2. 🔧 Solution Options:"
echo "---------------------"
echo "Option A: Add spark_user to 'all - database, udf' policy"
echo "Option B: Modify 'default database tables columns' policy priority"
echo "Option C: Create a new comprehensive policy for spark_user"
echo ""

echo "3. 🎯 Recommended Solution:"
echo "-------------------------"
echo "We will add spark_user to the 'all - database, udf' policy"
echo "This will give spark_user access to all databases and UDFs"
echo ""

echo "4. 📝 Manual Steps Required:"
echo "---------------------------"
echo ""
echo "1. 🌐 Access Ranger Admin UI:"
echo "   URL: http://localhost:6080"
echo "   Username: admin"
echo "   Password: rangeradmin1"
echo ""
echo "2. 📋 Navigate to Hive Service:"
echo "   - Go to 'Access Manager' → 'Resource Based Policies'"
echo "   - Click on 'hive' service"
echo ""
echo "3. 🔧 Edit 'all - database, udf' Policy:"
echo "   - Find policy 'all - database, udf'"
echo "   - Click 'Edit'"
echo "   - In 'Users' field, add: spark_user"
echo "   - Save the policy"
echo ""
echo "4. 🧪 Test the fix:"
echo "   docker exec -it hive-metastore /opt/hive/bin/beeline -u \"jdbc:hive2://spark-thrift-server:10000\" -n spark_user"
echo ""
echo "5. 📊 Expected Result:"
echo "   - spark_user should be able to connect"
echo "   - SHOW DATABASES; should work"
echo "   - CREATE TABLE should work"
echo ""

echo "5. 🔍 Alternative Quick Fix:"
echo "---------------------------"
echo "If you want to test immediately, you can also:"
echo ""
echo "1. 🌐 Go to Ranger Admin UI"
echo "2. 📋 Find the 'default database tables columns' policy"
echo "3. 🔧 Change 'isDenyAllElse' from false to true"
echo "4. 🧪 Test the connection"
echo ""

echo "6. 📋 Current Policy Status:"
echo "--------------------------"
echo "✅ spark_user has policy: 'default database tables columns'"
echo "❌ But 'all - database, udf' policy denies all others"
echo "❌ spark_user not in 'all - database, udf' allowed users"
echo ""

echo "7. 🚀 Next Steps:"
echo "---------------"
echo "1. Follow the manual steps above"
echo "2. Add spark_user to 'all - database, udf' policy"
echo "3. Test the connection"
echo "4. Verify access to default database"
echo ""
echo "The issue is that Ranger has a global deny policy that overrides the specific allow policy!" 