# BUILD: docker build --rm -t docker.citigo.com.vn/bi/docker-airflow:[version] -f Dockerfile .
# PUSH TO DOCKER_HUB:
## Run (if not login): docker login docker.citigo.com.vn
## Run: docker push docker.citigo.com.vn/bi/docker-airflow:[version]

FROM apache/airflow:2.6.1

USER root
# RUN cd /opt && curl -L -b "oraclelicense=a" http://download.oracle.com/otn-pub/java/jdk/8u131-b11/d54c1d3a095b4ff2b6607d096fa80163/jdk-8u131-linux-x64.tar.gz -O && \
# tar xzf jdk-8u131-linux-x64.tar.gz
COPY java/jdk1.8.0_131 /opt/jdk1.8.0_131

RUN cd /opt/jdk1.8.0_131 && update-alternatives --install /usr/bin/java java /opt/jdk1.8.0_131/bin/java 2 && \
update-alternatives --config java && \
update-alternatives --install /usr/bin/jar jar /opt/jdk1.8.0_131/bin/jar 2 && \
update-alternatives --install /usr/bin/javac javac /opt/jdk1.8.0_131/bin/javac 2 && \
update-alternatives --set jar /opt/jdk1.8.0_131/bin/jar && \
update-alternatives --set javac /opt/jdk1.8.0_131/bin/javac && \
echo "export JAVA_HOME=/opt/jdk1.8.0_131" >> ~/.bashrc && \
echo "export JRE_HOME=/opt/jdk1.8.0_131/jre" >> ~/.bashrc && \
echo "export PATH=$PATH:/opt/jdk1.8.0_131/bin:/opt/jdk1.8.0_131/jre/bin" >> ~/.bashrc

# RUN cd /opt && \
# curl https://dlcdn.apache.org/hadoop/common/hadoop-3.3.1/hadoop-3.3.1.tar.gz > hadoop.tar.gz  && \
# tar xzf hadoop.tar.gz && \
# mv hadoop-3.3.1 hadoop
RUN cd /opt
COPY hadoop/hadoop /opt/hadoop
COPY config/hadoop-env.sh /opt/hadoop/etc/hadoop/hadoop-env.sh
COPY config/hdfs-site.xml /opt/hadoop/etc/hadoop/hdfs-site.xml
COPY libs/gcs-connector-hadoop3-2.2.2-shaded.jar /opt/hadoop/share/hadoop/common/gcs-connector-hadoop3-2.2.2-shaded.jar
RUN mkdir /opt/libs
COPY libs/kvanalyzer-0.7.0-py3-none-any.whl /opt/libs/kvanalyzer-0.7.0-py3-none-any.whl

RUN apt-get update \
  && apt-get install -y --no-install-recommends \
         build-essential libopenmpi-dev heimdal-dev\
  && apt-get autoremove -yqq --purge \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*
RUN pip3 install cmake==3.26.3
RUN apt-get install gcc -y

# with root install libs for sasl
RUN apt-get update && apt-get install libsasl2-dev
RUN apt-get install libsasl2-2
RUN apt-get install libsasl2-modules-gssapi-mit
RUN pip3 install pip==23.1.2

RUN pip3 install wheel setuptools --upgrade

RUN apt-get install redis -y

USER airflow
COPY requirements.txt /
RUN pip3 install /opt/libs/kvanalyzer-0.7.0-py3-none-any.whl
RUN pip3 install -r /requirements.txt

